version: "3.3"
services:
  aria2:
    container_name: aria2
    image: aria2pro:1
#    image: registry.wtvdev.com/pub/aria2pro
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=010
      - RPC_SECRET=Aria_314
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - SPECIAL_MODE=move
      - TZ=Asia/Shanghai
      - RMQ_NAMESERVERS=http://127.0.0.1/mock
      - RMQ_TOPIC=topic1
      - RMQ_GROUP=group1
      - RMQ_KEY=key1
      - RMQ_SECRET=secret1
    ports:
      - "680:80/tcp"
      - "6800:6800/tcp"
      - "6888:6888/udp"
      - "6888:6888/tcp"
    volumes:
      - ${PWD}/nginx:/usr/local/openresty/nginx
      - ${PWD}/data/config:/config
      - ${PWD}/data/downloads:/downloads
      - ${PWD}/data/logs/:/data/logs/
  aria2pro:
    container_name: aria2pro
    image: registry.wtvdev.com/pub/aria2pro
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=010
      - RPC_SECRET=Aria_315
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - SPECIAL_MODE=move
      - TZ=Asia/Shanghai
      - RMQ_NAMESERVERS=http://127.0.0.1/mock
      - RMQ_TOPIC=topic1
      - RMQ_GROUP=group1
      - RMQ_KEY=key1
      - RMQ_SECRET=secret1
#    network_mode: host
    ports:
      - "680:680/tcp"
      - "6800:6800/tcp"
      - "6888:6888/udp"
      - "6888:6888/tcp"
    volumes:
      - ${PWD}/data/config:/config
      - ${PWD}/data/downloads:/downloads
      - ${PWD}/data/logs/:/data/logs/
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 5m

