version: "3.3"

services:
  aria2:
    container_name: aria2
    image: aria2pro:1
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=010
      - RPC_SECRET=Aria_314
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - SPECIAL_MODE=move
      - TZ=Asia/Shanghai
    ports:
      - "680:80/tcp"
      - "6800:6800/tcp"
      - "6888:6888/udp"
      - "6888:6888/tcp"
    volumes:
      - ${PWD}/nginx:/usr/local/openresty/nginx
      - ${PWD}/data/config:/config
      - ${PWD}/data/downloads:/downloads
  Aria2-Pro:
    container_name: aria2-pro
#    image: p3terx/aria2-pro
    image: aria2pro:1
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=010
      - RPC_SECRET=Aria_317
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=move
    volumes:
      - ${PWD}/config1:/config
      - ${PWD}/aria2-downloads:/downloads
    ports:
      - "680:80/tcp"
      - "6800:6800/tcp"
      - "6888:6888/udp"
      - "6888:6888/tcp"
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
